services:
  ytflex:
    build: .
    container_name: ytflex
    restart: always
    ports:
      - "2002:2002"
    volumes:
      - /app/ytflex/:/app/mountpoint/
    depends_on:
      - bgutil-provider

  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider
    container_name: bgutil-provider
    restart: always