name: Build, Push and Deploy

on: [push]

jobs:
  build-and-push-image:
    runs-on: penguin-devops
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kirellkekw
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kirellkekw/test-image:${{ github.sha }}

  replace-live-image:
    runs-on: penguin-devops
    steps:
      - uses: actions/checkout@v4

      - name: Stop Old Container
        run: docker stop ytflex

      - name: Remove Old Container
        if: always()
        run: docker rm ytflex

      - name: Pull New Docker Image
        if: always()
        run: docker pull kirellkekw/ytflex:${{ github.sha }}

      - name: Run New Docker Image
        if: always()
        run: docker run --detach --restart always --name ytflex --publish 2002:2002 --volume /softdisk/beer/cdn_root:/downloads kirellkekw/ytflex:${{ github.sha }}
