name: Deploy to Server

on: [push]

jobs:
  replace-live-image:
    runs-on: penguin-devops
    steps:
      - uses: actions/checkout@v4

      - name: Stop Old Container
        run: docker stop ytflex

      - name: Remove Old Container
        if: always()
        run: docker rm ytflex

      - name: Create New Image
        if: always()
        run: docker build -t ytflex .

      - name: Run New Image
        if: always()
        run: docker compose up -d -e REV_HASH=${{ github.sha }}