name: Push Docker Image to Server

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: penguin-devops

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: http://5.178.111.177:5000
          username: ${{ secrets.PENGUIN_USER }}
          password: ${{ secrets.PENGUIN_PASSWD }}

      - name: Stop Current Container
        if: always()
        run: docker stop ytflex

      - name: Remove Current Container
        if: always()
        run: docker rm ytflex

      - name: Build and Push Image
        if: always()
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 5.178.111.177:5000/ytflex:${{ github.sha }}

      - name: Run Docker Image
        if: always()
        # docker run -d -p 2002:2002 -v /designated/download/path/:/downloads yt_api:1.0.0
        run: docker run --detach --name ytflex --publish 2002:2002 --volume /softdisk/beer/cdn_root:/downloads 5.178.111.177:5000/ytflex:${{ github.sha }}
