name: Deploy to Server

on: [push]

jobs:
  replace-live-image:
    runs-on: penguin-devops
    steps:
      - uses: actions/checkout@v4

      - name: Stop Old Container
        run: docker stop ytflex || true

      - name: Remove Old Container
        run: docker rm ytflex || true

      - name: Add Environment Variables
        run: echo "REV_HASH = \"${{ github.sha }}\"" >> .env

      - name: Create New Image
        run: docker build -t ytflex .

      - name: Run New Image
        run: docker compose up -d