name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: penguin-devops

    steps:
      - uses: actions/checkout@v4

      - name: Test step
        run: whoami

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: http://5.178.111.177:5000
          username: ${{ secrets.PENGUIN_USER }}
          password: ${{ secrets.PENGUIN_PASSWD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 5.178.111.177:5000/ytflex:${{ github.sha }}

      - name: Replace Live Image
        run: nix flake update /etc/nixos

      - name: Upgrade System
        run: systemctl start nixos-upgrade.service

    #   - name: Rebuild System
    #     run: nixos-rebuild switch
